apiVersion: v1
kind: Service
metadata:
  name: {{ include "jbank-product.fullname" . }}
  labels:
    {{- include "jbank-product.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "jbank-product.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
