/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customerId}/edd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerEdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeStatus"];
        trace?: never;
    };
    "/api/v1/customers/{customerId}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetail"];
        put?: never;
        post?: never;
        delete: operations["close"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CustomerRegisterRequest: {
            name: string;
            residentRegNo: string;
            /** Format: date */
            birthDate: string;
            phone: string;
            address?: string;
            occupation?: string;
            /** @enum {string} */
            identityVerificationMethod: "FACE_TO_FACE" | "NON_FACE_TO_FACE";
            transactionPurpose?: string;
            fundSource?: string;
        };
        ApiResponseCustomerRegisterResponse: {
            success?: boolean;
            data?: components["schemas"]["CustomerRegisterResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        CustomerRegisterResponse: {
            customerId?: string;
            /** @enum {string} */
            kycGrade?: "GENERAL" | "CDD" | "EDD";
            /** @enum {string} */
            amlRiskLevel?: "LOW" | "MEDIUM" | "HIGH";
            /** @enum {string} */
            status?: "ACTIVE" | "DORMANT" | "CLOSED";
            eddRequired?: boolean;
        };
        ErrorDetail: {
            code?: string;
            message?: string;
        };
        EddRegisterRequest: {
            transactionPurpose: string;
            fundSource: string;
            supportingDocumentRef: string;
        };
        ApiResponseEddRegisterResponse: {
            success?: boolean;
            data?: components["schemas"]["EddRegisterResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        EddRegisterResponse: {
            customerId?: string;
            /** @enum {string} */
            amlRiskLevel?: "LOW" | "MEDIUM" | "HIGH";
            /** Format: date-time */
            eddCompletedAt?: string;
        };
        AccountOpenRequest: {
            customerId: string;
            /** @enum {string} */
            productType: "CHECKING";
            initialDeposit: number;
        };
        AccountOpenResponse: {
            accountId?: string;
            accountNumber?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            /** Format: date-time */
            openedAt?: string;
        };
        ApiResponseAccountOpenResponse: {
            success?: boolean;
            data?: components["schemas"]["AccountOpenResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        AccountStatusChangeRequest: {
            /** @enum {string} */
            targetStatus: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            reason?: string;
        };
        AccountStatusChangeResponse: {
            accountId?: string;
            /** @enum {string} */
            previousStatus?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
        };
        ApiResponseAccountStatusChangeResponse: {
            success?: boolean;
            data?: components["schemas"]["AccountStatusChangeResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageResponseCustomerAccountSummaryResponse: {
            success?: boolean;
            data?: components["schemas"]["PageResponseCustomerAccountSummaryResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        CustomerAccountSummaryResponse: {
            accountId?: string;
            accountNumber?: string;
            customerId?: string;
            /** @enum {string} */
            productType?: "CHECKING";
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            /** Format: date-time */
            openedAt?: string;
            /** Format: date-time */
            closedAt?: string;
            balance?: number;
            holdAmount?: number;
            availableBalance?: number;
            /** Format: date-time */
            asOf?: string;
        };
        PageResponseCustomerAccountSummaryResponse: {
            content?: components["schemas"]["CustomerAccountSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        AccountDetailResponse: {
            accountId?: string;
            accountNumber?: string;
            customerId?: string;
            /** @enum {string} */
            productType?: "CHECKING";
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            /** Format: date-time */
            openedAt?: string;
            /** Format: date-time */
            closedAt?: string;
        };
        ApiResponseAccountDetailResponse: {
            success?: boolean;
            data?: components["schemas"]["AccountDetailResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        AccountCloseResponse: {
            accountId?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            /** Format: date-time */
            closedAt?: string;
        };
        ApiResponseAccountCloseResponse: {
            success?: boolean;
            data?: components["schemas"]["AccountCloseResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerRegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCustomerRegisterResponse"];
                };
            };
        };
    };
    registerEdd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EddRegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEddRegisterResponse"];
                };
            };
        };
    };
    open: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountOpenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountOpenResponse"];
                };
            };
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountStatusChangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountStatusChangeResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query: {
                status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseCustomerAccountSummaryResponse"];
                };
            };
        };
    };
    getDetail: {
        parameters: {
            query: {
                customerId: number;
            };
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountDetailResponse"];
                };
            };
        };
    };
    close: {
        parameters: {
            query: {
                customerId: number;
            };
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountCloseResponse"];
                };
            };
        };
    };
}
