/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 고객 등록
         * @description 신규 고객을 등록하고 CDD(고객확인)를 함께 수행합니다. 인증이 필요 없습니다.
         *     같은 실명번호로 다시 등록하면 409(ACC_001)가 납니다.
         *     응답의 eddRequired가 true면 계좌 개설 전에 /edd API를 먼저 호출해야 합니다.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customerId}/edd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 강화된 고객확인(EDD) 등록
         * @description 고위험으로 분류된 고객만 호출할 수 있습니다. 고위험이 아닌 고객이면
         *     409(ACC_004)가 납니다. 정상 처리되면 계좌 개설 게이트가 풀립니다.
         */
        post: operations["registerEdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 계좌 개설
         * @description 고객의 CDD 완료 여부와 상태를 확인한 뒤 계좌를 개설합니다.
         *     W1 기준 초기 입금은 0원만 지원합니다(그 외 금액은 400).
         */
        post: operations["open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 계좌 상태변경
         * @description ACTIVE↔SUSPENDED, ACTIVE/SUSPENDED→DORMANT, DORMANT→ACTIVE만 허용합니다.
         *     CLOSED로의 전환은 이 API로 할 수 없습니다(해지 API를 쓰세요). 허용되지 않는
         *     전이는 409(ACC_007)가 납니다.
         */
        patch: operations["changeStatus"];
        trace?: never;
    };
    "/api/v1/customers/{customerId}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 고객별 계좌 목록 조회
         * @description 한 고객이 보유한 계좌를 페이지 단위로 조회합니다. status 쿼리 파라미터로
         *     특정 상태(ACTIVE, SUSPENDED 등)만 필터링할 수 있습니다. 원장이 아직 없어
         *     balance·holdAmount·availableBalance는 항상 0입니다(W2에서 실제 값 반영).
         */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 계좌 상세조회
         * @description 인증이 아직 없어 소유자 확인용 customerId를 쿼리 파라미터로 함께 보내야 합니다. 소유자가 아니면 403.
         */
        get: operations["getDetail"];
        put?: never;
        post?: never;
        /**
         * 계좌 해지
         * @description 잔액과 지급정지 금액이 모두 0원이어야 해지할 수 있습니다. 소유자 확인용 customerId가 필요합니다.
         */
        delete: operations["close"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CustomerRegisterRequest: {
            name: string;
            residentRegNo: string;
            /** Format: date */
            birthDate: string;
            phone: string;
            address?: string;
            occupation?: string;
            /** @enum {string} */
            identityVerificationMethod: "FACE_TO_FACE" | "NON_FACE_TO_FACE";
            transactionPurpose?: string;
            fundSource?: string;
        };
        ApiResponseCustomerRegisterResponse: {
            success?: boolean;
            data?: components["schemas"]["CustomerRegisterResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        CustomerRegisterResponse: {
            customerId?: string;
            /** @enum {string} */
            kycGrade?: "GENERAL" | "CDD" | "EDD";
            /** @enum {string} */
            amlRiskLevel?: "LOW" | "MEDIUM" | "HIGH";
            /** @enum {string} */
            status?: "ACTIVE" | "DORMANT" | "CLOSED";
            eddRequired?: boolean;
        };
        ErrorDetail: {
            code?: string;
            message?: string;
        };
        EddRegisterRequest: {
            transactionPurpose: string;
            fundSource: string;
            supportingDocumentRef: string;
        };
        ApiResponseEddRegisterResponse: {
            success?: boolean;
            data?: components["schemas"]["EddRegisterResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        EddRegisterResponse: {
            customerId?: string;
            /** @enum {string} */
            amlRiskLevel?: "LOW" | "MEDIUM" | "HIGH";
            /** Format: date-time */
            eddCompletedAt?: string;
        };
        AccountOpenRequest: {
            customerId: string;
            /** @enum {string} */
            productType: "CHECKING";
            initialDeposit: number;
        };
        AccountOpenResponse: {
            accountId?: string;
            accountNumber?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            /** Format: date-time */
            openedAt?: string;
        };
        ApiResponseAccountOpenResponse: {
            success?: boolean;
            data?: components["schemas"]["AccountOpenResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        AccountStatusChangeRequest: {
            /** @enum {string} */
            targetStatus: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            reason?: string;
        };
        AccountStatusChangeResponse: {
            accountId?: string;
            /** @enum {string} */
            previousStatus?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
        };
        ApiResponseAccountStatusChangeResponse: {
            success?: boolean;
            data?: components["schemas"]["AccountStatusChangeResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageResponseCustomerAccountSummaryResponse: {
            success?: boolean;
            data?: components["schemas"]["PageResponseCustomerAccountSummaryResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        CustomerAccountSummaryResponse: {
            accountId?: string;
            accountNumber?: string;
            customerId?: string;
            /** @enum {string} */
            productType?: "CHECKING";
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            /** Format: date-time */
            openedAt?: string;
            /** Format: date-time */
            closedAt?: string;
            balance?: number;
            holdAmount?: number;
            availableBalance?: number;
            /** Format: date-time */
            asOf?: string;
        };
        PageResponseCustomerAccountSummaryResponse: {
            content?: components["schemas"]["CustomerAccountSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        AccountDetailResponse: {
            accountId?: string;
            accountNumber?: string;
            customerId?: string;
            /** @enum {string} */
            productType?: "CHECKING";
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            /** Format: date-time */
            openedAt?: string;
            /** Format: date-time */
            closedAt?: string;
        };
        ApiResponseAccountDetailResponse: {
            success?: boolean;
            data?: components["schemas"]["AccountDetailResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        AccountCloseResponse: {
            accountId?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
            /** Format: date-time */
            closedAt?: string;
        };
        ApiResponseAccountCloseResponse: {
            success?: boolean;
            data?: components["schemas"]["AccountCloseResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerRegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCustomerRegisterResponse"];
                };
            };
        };
    };
    registerEdd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EddRegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEddRegisterResponse"];
                };
            };
        };
    };
    open: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountOpenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountOpenResponse"];
                };
            };
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountStatusChangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountStatusChangeResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query: {
                /** @description 필터링할 계좌 상태, 생략하면 전체 조회 */
                status?: "ACTIVE" | "SUSPENDED" | "DORMANT" | "CLOSED";
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseCustomerAccountSummaryResponse"];
                };
            };
        };
    };
    getDetail: {
        parameters: {
            query: {
                /** @description 임시 소유자 확인용 (W3에서 세션으로 대체 예정) */
                customerId: number;
            };
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountDetailResponse"];
                };
            };
        };
    };
    close: {
        parameters: {
            query: {
                /** @description 임시 소유자 확인용 (W3에서 세션으로 대체 예정) */
                customerId: number;
            };
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountCloseResponse"];
                };
            };
        };
    };
}
